version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lime-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lime-network

volumes:
  postgres_data:

networks:
  lime-network:
    driver: bridge
